---
- name: Deploy Docker Compose Stack
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Cleanup existing Docker containers
      shell: |
        docker rm -f imagecapdb imagecap-service model-service imagecapapp || true

    - name: Cleanup specific Docker images
      shell: |
        docker images -q rishithaiiitb/bemodel rishithaiiitb/backend rishithaiiitb/frontend | xargs -r docker rmi -f || true

    - name: Prune unused Docker images
      shell: docker image prune -f

    - name: Check if /ic directory exists
      stat:
        path: /ic
      register: ic_directory

    - name: Create Docker Compose working directory if it does not exist
      file:
        path: /ic
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: ic_directory.stat.exists == False

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/ImageCaptioning/docker-compose.yml
        dest: /ic/docker-compose.yml

    - name: Pull Model Service Image
      docker_image:
        name: rishithaiiitb/bemodel
        source: pull

    - name: Pull Backend Image
      docker_image:
        name: rishithaiiitb/backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: rishithaiiitb/frontend
        source: pull

    - name: Start Docker Compose Stack
      command: docker-compose up -d
      args:
        chdir: /ic/
